spring.application.name=shoestore
server.port=8080

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/shoe_store?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=3366
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE CONFIGURATION
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwtSecret=mySecretKeyForHS256AtLeast32BytesLong1234567890
app.jwtExpirationMs=86400000